### ISSUE TITLE
How to use/add this library?

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/KoreVideo#2]
Hi Robert,

currently trying to add this library in a test project at work, and i'm not quite sure how it's supposed to be used. I copied KoreVideo to my root folder, so it looks like:

``` haxe
[MyProject]
    [Kha]
    [KoreVideo]
    khafile.js
    korefile.js (generated by running 'node Kha/make --target windows')
```
- How do i say in the khafile.js to add this library (so korefile.js changes won't get overwritten)?
- So i edited the korefile.js to add a sub project next to Kha and Kha/Kore

``` haxe
project.addSubProject(Solution.createProject('...long path.../KoreVideo')); 
```

When i try to compile i get diffrent errors depending on the order of added subprojects
- 1) Kha; Kha/Kore; KoreVideo => multiple definitions of Kore::Video ctor, dtor, Kore::VideoSoundStream, etc
- 2) Kha; KoreVideo; Kha/Kore => recusive inclusion of `<Kore/pch.h>`
- 3) KoreVideo; Kha; Kha/Kore => recusive inclusion of `<Kore/pch.h>`

Then i went with 1) and changed `Kha/Kore/Backends/Windows/Sources/Kore/Video.h` and the `VideoSoundStream.h` header to something like

``` haxe
#ifndef KOREVIDEO
 ... existing stub definitions ...
#else
#include "../../../../../../KoreVideo/Sources/Kore/VideoSoundStream.h"
#endif
```

That hardcodes the path to KoreVideo now, which isn't that ideal imo.

Is it supposed to be used that way or did i miss anything?
Will it be integrated into Kha at some point or kept an extension?

**Comment by RobDangerous** [comment]
Oh, I didn't touch this in a while. The general plan is to use hardware video decoding wherever possible (currently it's implemented for iOS and Android) and keep KoreVideo as an extension for when that is not possible (Linux is a problem here) or not wanted.
